server:
  port: 7070
  servlet:
    context-path: /admin
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: weblive-admin
  datasource:
    url: jdbc:mysql://localhost:3306/weblive?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root     # 替换为你的mysql数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  kafka:
    bootstrap-servers: ip:9092   # 输入你的kafka服务器地址 ip:port
    # 配置生产者
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true  # 发送类型头，方便消费者反序列化
    # 配置消费者
    consumer:
      auto-offset-reset: earliest #自动将偏移量重置为最早的偏移量
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  #信任所有包
      enable-auto-commit: false #关闭自动提交偏移量，避免消息丢失
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
      timeout: 2000

#mybatis 大小写转驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


project:
  folder: D:/weblive-project/   #可以选择替换项目文件存放路径，注意最后的斜杠

es:
  host:
    port: ip:9200  # 替换为你的Elasticsearch服务器地址 ip:port
  index:
    video:
      name: weblive_video
  username: elastic
  password: 123456      # 替换为你的Elasticsearch密码

# 主题: weblive-transfer-file-queue 和 weblive-video-play-queue
# 消费者组: weblive-web-transfer 和 weblive-web-play
kafka:
  topic:
    transfer-file-queue: weblive-transfer-file-queue
    video-play-queue: weblive-video-play-queue

# 预设管理员账号密码
admin:
  account: admin
  password: admin

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: adminToken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  cookie:
    path: /

auth:
  noAuthUrls:
    - /account/login
    - /account/logout
    - /account/checkCode

#==============================邮箱配置=======================================
mail:
  smtp:
    host: smtp.163.com  #替换为你的邮箱SMTP服务器
    port: 25            #替换为你的邮箱SMTP端口
    email: test@163.com #替换为你的邮箱账号
    password: test  #替换为你的邮箱授权码