server:
  port: 7070
  servlet:
    context-path: /admin
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: weblive-admin
  datasource:
    url: jdbc:mysql://localhost:3306/weblive?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root     # 替换为你的mysql数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  kafka:
    bootstrap-servers: ip:9092   # 输入你的kafka服务器地址 ip:port
    # 配置生产者
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true  # 发送类型头，方便消费者反序列化
    # 配置消费者
    consumer:
      auto-offset-reset: earliest #自动将偏移量重置为最早的偏移量
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  #信任所有包
      enable-auto-commit: false #关闭自动提交偏移量，避免消息丢失
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
      timeout: 2000

#mybatis 大小写转驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


project:
  folder: D:/weblive-project/   #可以选择替换项目文件存放路径，注意最后的斜杠

es:
  host:
    port: ip:9200  # 替换为你的Elasticsearch服务器地址 ip:port
  index:
    video:
      name: weblive_video
  username: elastic
  password: 123456      # 替换为你的Elasticsearch密码

# 主题: weblive-transfer-file-queue 和 weblive-video-play-queue
# 消费者组: weblive-web-transfer 和 weblive-web-play
kafka:
  topic:
    transfer-file-queue: weblive-transfer-file-queue
    video-play-queue: weblive-video-play-queue

# 预设管理员账号密码
admin:
  account: admin
  password: admin